# spring application properties
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    com.devadmin:  INFO

# jira connection
jira:
  cloud-url: https://devadmin.atlassian.net
  username: serpento@devadmin.com
  password: Gz4815162342
# slack integration
slack:
  api-url: https://slack.com/api
  token:
    bot: xoxb-3666444034-479068848033-MZlRM9K6jKJaPrc8wVlp1eat
    verification: wdwRLHJvrHVyBq60DmGsq0z4
  webhook:
    incoming:
      directMessage: https://hooks.slack.com/services/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
      white: https://hooks.slack.com/services/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
      tools: https://hooks.slack.com/services/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