spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    com.devadmin: DEBUG

# slack integrations
slackApi: https://slack.com/api
slackBotToken: xoxb-474918643861-474558953648-o2Kp1eOHbSS7XxrVVf5l7t5a
slashCommandToken: SP99f9lA5YGKfSOgg99KxmZ9