spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    com.devadmin: DEBUG

# slack integrations
slackApi: https://slack.com/api
slackBotToken: xoxb-474918643861-475541422883-usfjTM70X0vFMtoGQZUYzzFn
slashCommandToken: Ep4sbvaoE7e6G0aCP13A0QLd

# jira integration
jiraUsername: hzq44243@nbzmr.com
jiraPassword: 123456654321
jiraToken: 3456