spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    com.devadmin: DEBUG

# slack integrations
slackApi: https://slack.com/api
slackBotToken: <your slack bot token>
slashCommandToken: <your slack slash command token>
slackIncomingWebhookUrl: <your slack incomming webhook token>

# jira integration
jiraUrl: <yourdomain.atlassian.net>
jiraUsername: <your jira username>
jiraPassword: <your jira password>