# spring application properties
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    com.devadmin: INFO


# jira integration
jira:
  cloud-url: https://devadmin.atlassian.net
  username: lollipop@devadmin.com
  password: FXtTYFJpN0LA5DMsgMvW9E3B

# slack integration
slack:
  api-url: https://slack.com/api
  token:
    bot: xoxb-3666444034-964922925542-I1c7DPZox8ORUkQWg51ekMU2
    verification: bU520K0ZNUoDvrNTsNMlghP7
  notification:
    task-types:
      atReference: 13,10100
      commentedTask: 13,10100
      createdTask: 13,10100
      labeledTask: 13,10100
      pmOnAssign: 13,10100
      resolvedTask: 13,10100
# server properties
server:
  tomcat:
    uri-encoding: UTF-8

debug:
  message-service:
    additional-information: mrfox

statuses:
  available:
    emoji: ':rocket:'
    text: Available
    expiration: 8